USE [NTTMPBase]
GO

SELECT [Id]
      ,[OrderId]
      ,[ProdOrderNo]
      ,[PartNumber]
      ,[ProcessSeg]
      ,[ProductLineNo]
      ,[PlantCode]
      ,[LineMode]
      ,[ProcessNo]
      ,[DeviceNo]
      ,[LastFlag]
      ,[TotalNum]
      ,[GoodNum]
      ,[FirstGoodNum]
      ,[TotalNumFromLast]
      ,[GoodNumFromLast]
      ,[FirstGoodNumFromLast]
      ,[LastTime]
      ,[LastPLCFlag]
      ,[CtrlFlag]
      ,[LastRMCount]
      ,[LastGoodCount]
      ,[LastFailCount]
      ,[RMUseNum]
      ,[PLCGoodNum]
      ,[PLCFailNum]
      ,[MinCT]
      ,[MaxCT]
      ,[CreateBy]
      ,[CreateTime]
      ,[UpdateBy]
      ,[UpdateTime]
      ,[IsDelete]
      ,[RMReduceFlag]
      ,[InvalidFlag]
  FROM [dbo].[TP_Now_OrderStatus]

GO

